services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mjbquieta}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mjbquieta}
      POSTGRES_DB: ${POSTGRES_DB:-moneytrackerdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prospera.local
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
